### ISSUE TITLE
Add option to hide on small screens.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-top-bar#11]

**Comment by dannyvankooten** [comment]
Right now, people can add the following CSS to hide the bar on screens smaller than 600px.

```css
@media( max-width: 600px ) {
	#mailchimp-top-bar { display: none !important; }
}
```
