### ISSUE TITLE
top bar hides menu on mobile

### ISSUE THREAD

**Issue by sawyer704** [ibericode/mailchimp-top-bar#26]
The top-bar hides the menu on mobile. The little triangle is too subtle for folks to toggle to hide the top bar.

**Comment by dannyvankooten** [comment]
Hi @sawyer704 , do you have a link where I can see this happening? This is highly dependent on your theme, that's why I'm asking. :)

As for the toggle icon, you can control the color & size of the icon by adding something like the following to your theme CSS.

```css
#mailchimp-top-bar .mctb-close {
	color: red;
	font-size: 26px;
}
```
