### ISSUE TITLE
Internet Explorer Display Bug

### ISSUE THREAD

**Issue by chrislowthian** [ibericode/mailchimp-top-bar#46]
Just viewed a website I am working on for someone in Internet Explorer (11) and the site displays embedded Youtube Videos. Unfortunately the videos end up in front of the Top Bar.

I have tried in Google Chrome and Safari and this does not happen.

Is there an easy fix for this?

![topbar-ie-bug](https://cloud.githubusercontent.com/assets/9029748/11919506/226bbcb6-a74d-11e5-8bd9-70941e575d94.png)

**Comment by dannyvankooten** [comment]
Hey @chrislowthian ,

Unfortunately this is super specific to your theme, I'm guessing the video has a super high `z-index` which makes the video appear on top of the bar.

Does adding the following CSS to your theme do anything?

```css
.mctb { z-index: 9999999999999 !important; }
video, iframe{ z-index: 100 !important; }
```
